#!/bin/sh

CURRENT_DIR="$(cd "$(dirname "${0}")" && pwd)"
tests_exit_value="0"

_run_vagrant() {
    vagrant up
}

# Halt vagrant after tests are done running, unless KEEP_RUNNING environment
# variable is set to 'true'.
_stop_vagrant() {
    [ -z "${KEEP_RUNNING}" ] && vagrant halt
}

_run_tests() {
    vagrant ssh -c "cd ~/tpm; ./tests/run-tests-within-vm"
    tests_exit_value="${?}"
}

_run_vagrant
_run_tests
_stop_vagrant
exit "${tests_exit_value}"

# vim: set ts=8 sw=4 tw=0 ft=sh :
