#!/usr/bin/env expect

#disables script output
log_user 0

spawn tmux

#Waiting for tmux to attach.
sleep 1

#this is tmux prefix + U
send "U"

set timeout 5

expect {
  "Installed plugins" {
    expect {
      "\"tmux-example-plugin\"" {
        expect {
          "\"all\" - updates all plugins" {
            expect { "ENTER - cancels" }
          }
        }
      }
    }
  }

  timeout {
    puts "tests/plugin_update_single.exp: Couldn't see the update prompt, timeout";
    exit 1
  }
}

send "tmux-example-plugin\r"

expect {
  "Updating \"tmux-example-plugin\"" {
    expect {
      "\"tmux-example-plugin\" update success" {
        expect { "Done, press ENTER to continue." { exit 0 } }
      }
    }
  }

  timeout {
    puts "tests/plugin_update_single.expt: Couldn't update the 'tmux-example-plugin' plugin, timeout";
    exit 1
  }
}
