#!/usr/bin/env expect

#disables script output
log_user 0

spawn tmux

#Waiting for tmux to attach.
sleep 1

#this is tmux prefix + I
send "I"

#cloning might take a while
set timeout 30

expect {
  "Installing \"tmux-sensible\"" {
    expect {
      "\"tmux-sensible\" download success" {
        expect { "Done, press ENTER to continue" {
            send ""
          }
        }
      }
    }
  }

  timeout {
    puts "tests/plugin_install.exp: Couldn't install tmux-sensible, timeout";
    exit 1
  }
}

#after tmux-sensible is installed the new prefix is Ctrl+a
send "I"

expect {
  "Already installed \"tmux-sensible\"" {
    expect { "Done, press ENTER to continue" { exit 0 } }
  }

  timeout {
    puts "tests/plugin_install.exp: Couldn't re-install tmux-sensible, timeout";
    exit 1
  }
}
