#!/usr/bin/env expect

#disables script output
log_user 0

spawn tmux

#Waiting for tmux to attach.
sleep 1

#this is tmux prefix + U after tmux-sensible
send "U"

set timeout 30

expect {
    "Installed plugins" {
expect {
    "\"tmux-sensible\"" {
expect {
    "\"sha1sum.txt\"" {
expect {
    "\"meta-micro\"" {
expect {
    "\"README.TXT\"" {
expect {
    "\"run_tests\"" {
expect {
    "\"tmux-example-plugin\"" {
expect {
    "\"tmux-online-status\"" {
expect {
    "\"tmux-battery\"" {
expect {
    "\"tmux-sidebar\"" {
expect {
    "\"all\" - updates all plugins" {
    expect { "ENTER - cancels" }
          }}}}}}}}}}}}}}}}}}}}}

  timeout {
    puts "tests/plugin_update_all_extended.exp: Couldn't see the update prompt, timeout";
    exit 1
  }
}

send "all\r"

expect {
    "Updating all plugins!" {
expect {
    "Updating \"tmux-sensible\"" {
expect {
    "\"tmux-sensible\" update success" {
expect {
    "Updating \"sha1sum.txt\"" {
expect {
    "\"sha1sum.txt\" update success" {
expect {
    "Updating \"meta-micro\"" {
expect {
    "\"meta-micro\" update success" {
expect {
    "Updating \"README.TXT\"" {
expect {
    "\"README.TXT\" update success" {
expect {
    "Updating \"run_tests\"" {
expect {
    "\"run_tests\" update success" {
expect {
    "Updating \"tmux-example-plugin\"" {
expect {
    "\"tmux-example-plugin\" update success" {
expect {
    "Updating \"tmux-online-status\"" {
expect {
    "\"tmux-online-status\" update success" {
expect {
    "Updating \"tmux-battery\"" {
expect {
    "\"tmux-battery\" update success" {
expect {
    "Updating \"tmux-sidebar\"" {
expect {
    "\"tmux-sidebar\" update success" {
    expect { "Done, press ENTER to continue." { exit 0 } }
          }}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}

  timeout {
    puts "tests/plugin_update_all_extended.exp: Couldn't update 'all' plugins after the update prompt, timeout";
    exit 1
  }
}
