DEFAULT_TMUX_PLUGIN_MANAGER_PATH="${HOME}/.tmux/plugins/"

INSTALL_KEY_OPTION="@tundle-install"
DEFAULT_INSTALL_KEY="I"

UPDATE_KEY_OPTION="@tundle-update"
DEFAULT_UPDATE_KEY="U"

CLEAN_KEY_OPTION="@tundle-clean"
DEFAULT_CLEAN_KEY="M-u"

LIST_KEY_OPTION="@tundle-list"
DEFAULT_LIST_KEY="M-l"
